import { pretendard } from "@/theme/font";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body id="body" className="bg-bg-elevation2 h-screen antialiased">
        {children}
      </body>
    </html>
  );
}
